# Generated by Django 5.2.5 on 2025-08-15 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number_of_courts', models.PositiveIntegerField(verbose_name='Количество кортов')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Теннисный центр',
                'verbose_name_plural': 'Теннисные центры',
            },
        ),
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('tennis_center_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('court_id', models.IntegerField(blank=True, null=True)),
                ('trainer_service', models.BooleanField(default=False)),
                ('racket_rental', models.IntegerField(default=0)),
                ('balls_rental', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TennisCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.PositiveIntegerField(verbose_name='Номер корта')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час')),
                ('surface_type', models.CharField(choices=[('clay', 'Грунт'), ('hard', 'Хард'), ('grass', 'Трава')], max_length=10, verbose_name='Тип покрытия')),
                ('indoor', models.BooleanField(default=False, verbose_name='Крытый корт')),
                ('tennis_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='tennis.tenniscenter', verbose_name='Теннисный центр')),
            ],
            options={
                'verbose_name': 'Теннисный корт',
                'verbose_name_plural': 'Теннисные корты',
                'unique_together': {('tennis_center', 'court_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('duration_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Продолжительность (часы)')),
                ('trainer_service', models.BooleanField(default=False, verbose_name='Услуги тренера')),
                ('racket_rental', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Аренда ракеток')),
                ('balls_rental', models.BooleanField(default=False, verbose_name='Аренда мячей')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('cancelled', 'Отменено')], default='pending', max_length=10, verbose_name='Статус')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tennis_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.tenniscenter', verbose_name='Теннисный центр')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.tenniscourt', verbose_name='Корт')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
